trading/apps/base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from trading.apps.base import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new_trade/$', views.NewTradeView.as_view(), name='new_trade'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

trading/apps/base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.crypto import get_random_string
from django.db import models


class BookedTrade(models.Model):
    id = models.CharField(max_length=9, primary_key=True)
    sell_ccy = models.CharField(max_length=3)
    sell_amount = models.DecimalField(max_digits=10, decimal_places=2)
    buy_ccy = models.CharField(max_length=3)
    buy_amount = models.DecimalField(max_digits=10, decimal_places=2)
    rate = models.DecimalField(max_digits=7, decimal_places=4)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __unicode__(self):
        return str(self.created)

    def generate_custom_id(self):
        return u'{tag}{random_alphanum}'.format(
            tag=u'TR',
            random_alphanum=get_random_string(length=7)
        )

    def save(self, *args, **kwargs):
        self.id = self.generate_custom_id()
        super(BookedTrade, self).save(*args, **kwargs)

trading/apps/base/forms.py
import requests

from collections import OrderedDict

from django import forms
from .models import BookedTrade


def get_available_currencies():
    data = requests.get("http://api.fixer.io/latest")
    if data.status_code in [200]:
        all_currencies = sorted(data.json()['rates'].keys())
        options = [("", "")]  # first pos in dropdown needs to be empty string
        options.extend([(item, item) for item in all_currencies])
        return options
    return []

CHOICES = get_available_currencies()


class FunkyForm(object):
    """
    A funky form: add bootstrap classes to form fields.
    """
    def __init__(self, *args, **kwargs):
        super(FunkyForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})


class NewTradeForm(FunkyForm, forms.ModelForm):
    sell_ccy = forms.CharField(widget=forms.Select(choices=CHOICES))
    sell_amount = forms.DecimalField()
    buy_ccy = forms.CharField(widget=forms.Select(choices=CHOICES))
    buy_amount = forms.CharField()
    rate = forms.CharField()

    class Meta:
        model = BookedTrade
        fields = ('sell_ccy', 'sell_amount', 'rate', 'buy_ccy', 'buy_amount')

    def __init__(self, *args, **kwargs):
        super(NewTradeForm, self).__init__(*args, **kwargs)
        self.fields['buy_amount'].widget.attrs['readonly'] = True
        self.fields = OrderedDict([
            (name, self.fields[name]) for name in self._meta.fields
        ])
        for name, field in self.fields.items():
            field.widget.attrs.update({'required': 'required'})

trading/apps/base/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import CreateView, ListView
from django.core.urlresolvers import reverse_lazy

from .models import BookedTrade
from .forms import NewTradeForm


class IndexView(ListView):
    template_name = 'base/index.html'
    model = BookedTrade
    http_method_names = [u'get']

    def get_queryset(self, *args, **kwargs):
        return self.model.objects.filter()


class NewTradeView(CreateView):
    http_method_names = [u'post', u'get']
    template_name = 'base/new_trade.html'
    model = BookedTrade
    form_class = NewTradeForm
    success_url = reverse_lazy('index')

trading/apps/base/templates/base/base.html
{% load staticfiles %}
{% load compress %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Ebury Trading{% endblock %}</title>

    <meta charset="utf-8">

	<meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

	<meta name="Author" content="iwannajoinebury.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <meta name="description" content="{% block meta_descr %}Trade with just 1 click.{% endblock %}">

    {% compress css %}
        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'libs/bootstrap/bootstrap-4.0.0-beta-dist/css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        {% endblock %}
    {% endcompress %}

    {% compress js %}
        {% block js %}
            <script type="text/javascript" src="{% static 'libs/money/money.js' %}"></script>
            <script type="text/javascript" src="{% static 'libs/jquery/jquery-1.11.3.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'libs/bootstrap/bootstrap-4.0.0-beta-dist/js/bootstrap.js' %}"></script>
        {% endblock %}
    {% endcompress %}

</head>
<body>
    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
</body>
</html>

trading/apps/base/templates/base/index.html
{% extends "base/base.html" %}

{% block content %}
<div role="main" class="container theme-showcase" style="width:900px; margin:0 auto;">
    
    <div class="page-header">
        <h3>Booked Trades</h3>
        <hr style="height:4px;border:none;color:#333;background-color:#333;" />
    </div>

    <div align="right">
        <a href={% url 'new_trade' %}>
        <button class="btn btn-xs btn-info" type="button">New Trade</button>
        </a>
    </div>

    </br> 

    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Sell CCY</th>
                        <th>Sell Amount</th>
                        <th>Buy CCY</th>
                        <th>Buy Amount</th>
                        <th>Rate</th>
                        <th>Date Booked</th>
                    </tr>
                </thead>
                <tbody>
                    {% for trade in object_list %}
                        <tr>
                            <td>{{trade.sell_ccy}}</td>
                            <td>{{trade.sell_amount}}</td>
                            <td>{{trade.buy_ccy}}</td>
                            <td>{{trade.buy_amount}}</td>
                            <td>{{trade.rate}}</td>
                            <td>{{trade.created|date:"d/m/Y H:i"}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}

{% block footer %}
<p align='center'> &copy 2017 iwannajoinebury.com </p>
{% endblock %}

trading/apps/base/templates/base/new_trade.html
{% extends "base/base.html" %}

{% block content %}
<div role="main" class="container theme-showcase" style="width:900px; margin:0 auto;">
    <div class="page-header">
        <h3>New Trade</h3>
        <hr/>
    </div>
    </br> 
   <div class="row">
        <div class="col-md-12">
            <form action="./" method="POST">
                {% csrf_token %}
                <div id="wrap" align="right">
                    <div id="leftPane">
                        <div>
                            <p align="center">Sell Currency</p>
                            {{ form.sell_ccy }}
                            </br>
                            <p align="center">Sell Amount</p>
                            {{ form.sell_amount }}
                            </br> </br>
                            <div class="form_control">
                                <button type="submit" class="btn btn-xs btn-success pull-left" type="button">Create</button>
                            </div>
                        </div>
                    </div>
                    <div id="midPane">
                        <p align="center">Rate</p>
                        {{ form.rate }}
                    </div>

                    <div id="rightPane">
                        <div>
                            <p align="center">Buy Currency</p>
                            {{ form.buy_ccy }}
                            </br>
                            <p align="center">Buy Amount</p>
                            {{ form.buy_amount }}
                            </br> </br>
                            <a href={% url 'index' %}>
                                <button class="btn btn-xs btn-danger pull-right" type="button">Cancel</button>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        function toggleDropdowns(event) {
            <!-- Sell Currency value is selected first -->
            if (event.target.id == "id_sell_ccy"){
                var source_curr = event.explicitOriginalTarget.value
                var target_curr = document.getElementById('id_buy_ccy').value
                if (target_curr != "") {
                    var new_rate = function(data) {
                          fx.rates = data.rates
                          var rate = fx(1).from(source_curr).to(target_curr)
                        var s = document.getElementById('id_rate')
                        s.innerHTML = rate.toFixed(4)
                    }

                    $.getJSON("http://api.fixer.io/latest", new_rate)
                }

            }

            <!-- Buy Currency value is selected first -->
            if (event.target.id == "id_buy_ccy"){
                var source_curr = event.explicitOriginalTarget.value
                var target_curr = document.getElementById('id_sell_ccy').value
                if (source_curr != "") {
                    var new_rate = function(data) {
                        fx.rates = data.rates
                        var rate = fx(1).from(source_curr).to(target_curr)
                        $("#id_rate").val(rate.toFixed(4));
                    }

                    $.getJSON("http://api.fixer.io/latest", new_rate)
                }
            }
        } 

        <!-- calculate the Buy Amount based on Sell Amount and rate -->
        function calculateBuyAmount(event) {
            var rate = $('#id_rate').val();
            var sell_amount = $('#id_sell_amount').val()


            if (rate != ""){
                var buy_amount = parseFloat(rate)  * parseFloat(sell_amount)
                $("#id_buy_amount").val(buy_amount.toFixed(2));
            }
        }

        document.getElementById('id_sell_ccy').addEventListener("change", toggleDropdowns);
        document.getElementById('id_buy_ccy').addEventListener("change", toggleDropdowns);
        document.getElementById('id_sell_amount').addEventListener("change", calculateBuyAmount);
    });
</script>
{% endblock %}


{% block footer %}
</br> </br>
<p align='center'> &copy 2017 iwannajoinebury.com </p>
{% endblock %}